### ISSUE TITLE
FindGLFW.cmake uses GLEW_ROOT_DIR instead of GLFW_ROOT_DIR

### ISSUE THREAD

**Issue by ghost** [lighttransport/nanogi#2]
It seems like FindGLFW.cmake is using GLEW instead of GLFW.
See here: https://github.com/lighttransport/nanogi/blob/master/cmake/FindGLFW.cmake#L45

**Comment by syoyo** [comment]
cc w/ @hi2p-perim

**Comment by syoyo** [comment]
Thank you for pointing out!
